feat: fix action bar buttons on mobile
conversionxl/sensei pull request #16
Opened 2024-03-25 15:36 UTC by anoblet

https://app.clickup.com/t/86azp8r7v

<img width="1720" alt="image" src="https://github.com/conversionxl/sensei/assets/7674171/e79fae87-db3e-4f22-ab83-5bd1fdf9725b">
<img width="1720" alt="Desktop" src="https://github.com/conversionxl/cxl-wpstarter/assets/7674171/6189cdc9-4807-4c3b-b0a4-980e2757071c">

2024-03-26 10:59 UTC, pawelkmpt requested changes
Code is fine, commit message needs adjustment.

```diff
- feat: fix action bar buttons on mobile
+ fix: action bar buttons on mobile
+
+ https://app.clickup.com/t/86azp8r7v
```

2024-03-27 10:38 UTC, pawelkmpt approved these changes

2024-03-27 10:38 UTC, merged

2024-03-27 14:39 UTC, paulkirspuu reviewed
Something breaks the buttons "Reset quiz" and "Save quiz" here.

2024-03-27 15:12 UTC, anoblet commented
I see this too. Simply wrapping the button text in a span breaks the save functionality.

```
<vaadin-button
	type="submit"
	name="quiz_save"
	class="quiz-submit save"
	theme="tertiary contrast"
>
	<span><?php esc_html_e( 'Save quiz', 'sensei-lms' ); ?></span>
</vaadin-button>
```